spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/packlister'
    username: postgres
    password: Hunter2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    defaultSchema: packlister
