server:
  port: ${PORT}
spring:
  datasource:
    url: ${DATABASE_CONNECTION_URL}
    username: ${DATABASE_CONNECTION_USERNAME}
    password: ${DATABASE_CONNECTION_PASSWORD}
  jpa:
    open-in-view: false # disable unless some need arises
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DATABASE_SCHEMA}
        jdbc:
          batch_size: 25
  flyway:
    defaultSchema: ${DATABASE_SCHEMA}
    locations: classpath:migrations
jwt:
  secret: ${JWT_SECRET}
management:
  endpoint:
    enabled-by-default: false # don't expose unwanted actuator endpoints
    health:
      enabled: true
