server:
  port: 8080
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/packlister'
    username: postgres
    password: Hunter2
  jpa:
    properties:
      hibernate:
        default_schema: packlister
#        format_sql: true
#        generate_statistics: true # get an idea of actual statements / batches since Hibernate logs can lie
  flyway:
    defaultSchema: packlister
packlister:
  auth:
    secure-cookie: false
    domain: localhost
    issuer: http://localhost:8080
    allowed-origin: http://localhost:3003
    jwt-secret: TCyqzjkid2QINz6ENYHa4lRecAg/x5KrQepKFYfw4x9+Q3Zn/4VIdsw1p9SeokU6VM4DSl32mlO6f0bo5kouXQ==
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        security: DEBUG
        web:
          cors: DEBUG
