server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DATABASE_CONNECTION_URL}
    username: ${DATABASE_CONNECTION_USERNAME}
    password: ${DATABASE_CONNECTION_PASSWORD}
  jpa:
    open-in-view: false # disable unless some need arises
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DATABASE_SCHEMA:packlister}
        jdbc:
          batch_size: 25
  flyway:
    defaultSchema: ${DATABASE_SCHEMA:packlister}
    locations: classpath:migrations
packlister:
  authserver:
    client-id: ${PACKLISTER_AUTHSERVER_CLIENT_ID}
    issuer: ${PACKLISTER_AUTHSERVER_ISSUER}
    allowed-redirect-uris: ${PACKLISTER_AUTHSERVER_ALLOWED_REDIRECT_URIS}
    rsa-private-key: ${PACKLISTER_AUTHSERVER_RSA_PRIVATE_KEY}
management:
  endpoint:
    enabled-by-default: false # don't expose unwanted actuator endpoints
    health:
      enabled: true
