server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DATABASE_CONNECTION_URL}
    username: ${DATABASE_CONNECTION_USERNAME}
    password: ${DATABASE_CONNECTION_PASSWORD}
  jpa:
    open-in-view: false # disable unless some need arises
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DATABASE_SCHEMA:packlister}
        jdbc:
          batch_size: 25
  flyway:
    defaultSchema: ${DATABASE_SCHEMA:packlister}
    locations: classpath:migrations
packlister:
  auth:
    secure-cookie: true
    domain: ${PACKLISTER_AUTH_DOMAIN}
    issuer: ${PACKLISTER_AUTH_ISSUER}
    allowed-origin: ${PACKLISTER_AUTH_ALLOWED_ORIGIN}
    jwt-secret: ${PACKLISTER_AUTH_JWT_SECRET}
management:
  endpoint:
    enabled-by-default: false # don't expose unwanted actuator endpoints
    health:
      enabled: true
